export class BudgetCorrectionSave {
    id: number;
    code: string;
    name: string;
    depPeriod: number;
    depPeriodRem: number;
    // employeeId: number;
    // projectId: number;
    // countryId: number;
    // activityId: number;
    // departmentId: number;
    // admCenterId: number;
    // regionId: number;
    // divisionId: number;
    // projectTypeId: number;
    // assetTypeId: number;
    // appStateId: number;
    // startAccMonthId: number;
    info: string;
    //validated: boolean;
    april: number;
    may: number;
    june: number;
    july: number;
    august: number;
    september: number;
    octomber: number;
    november: number;
    december: number;
    january: number;
    february: number;
    march: number;
    valueIni: number;
    aprilForecast: number;
    mayForecast: number;
    juneForecast: number;
    julyForecast: number;
    augustForecast: number;
    septemberForecast: number;
    octomberForecast: number;
    novemberForecast: number;
    decemberForecast: number;
    januaryForecast: number;
    februaryForecast: number;
    marchForecast: number;
    aprilForecastSrcNew: number;
    mayForecastSrcNew: number;
    juneForecastSrcNew: number;
    julyForecastSrcNew: number;
    augustForecastSrcNew: number;
    septemberForecastSrcNew: number;
    octomberForecastSrcNew: number;
    novemberForecastSrcNew: number;
    decemberForecastSrcNew: number;
    januaryForecastSrcNew: number;
    februaryForecastSrcNew: number;
    marchForecastSrcNew: number;
    aprilForecastDestination: number;
    mayForecastDestination: number;
    juneForecastDestination: number;
    julyForecastDestination: number;
    augustForecastDestination: number;
    septemberForecastDestination: number;
    octomberForecastDestination: number;
    novemberForecastDestination: number;
    decemberForecastDestination: number;
    januaryForecastDestination: number;
    februaryForecastDestination: number;
    marchForecastDestination: number;
    aprilForecastDstNew: number;
    mayForecastDstNew: number;
    juneForecastDstNew: number;
    julyForecastDstNew: number;
    augustForecastDstNew: number;
    septemberForecastDstNew: number;
    octomberForecastDstNew: number;
    novemberForecastDstNew: number;
    decemberForecastDstNew: number;
    januaryForecastDstNew: number;
    februaryForecastDstNew: number;
    marchForecastDstNew: number;
    budgetForecastId: number;
    budgetForecastDestinationId: number;
    budgetBaseOpId: number;
    srcEmployeeId: number;
    dstEmployeeId: number;

    totalForecast: any;
    totalForecastDestination: any;

    // needeedBudget: number;
    // budgetBaseNewId: number;
    //orderId: number;
    //requestBudgetForecastId: number;
    importValueOrder: number;
    valueOrder: number;
    valueAsset: number;
    totalRem: number;
    valueAssetYTD: number;
    valueAssetYTG: number;
    totalRemDestination: number;
    importValueOrderDestination: number;
    valueAssetYTDDestination: number;
    valueAssetYTGDestination: number;
    valueOrderDestination: number;
}
